// Controlled vocabulary for company enrichment search.
//
// Ported verbatim from the data-agent project
// (src/agent/taxonomy.py + src/agent/subtags.py) — the source of truth for how
// rows in the `company_enrichment` Supabase table were tagged. The query→filter
// extractor (server/services/pipeline/enrichmentFilter.ts) maps a user query
// onto these closed lists and validates every value against them before any DB
// query runs. Keep in sync with the data-agent when its PROMPT_VERSION bumps.

// Primary sector must be one of SECTORS. sector_tags[] may include any of these.
export const SECTORS = [
  "Banking & Financial Services",
  "Insurance",
  "Capital Markets & Asset Management",
  "Real Estate Development",
  "Construction & Engineering",
  "Oil & Gas - Upstream",
  "Oil & Gas - Downstream / Petrochemicals",
  "Power & Utilities",
  "Telecommunications",
  "Technology & Software",
  "Consumer Goods",
  "Retail & E-Commerce",
  "Hospitality, Travel & Tourism",
  "Healthcare & Pharmaceuticals",
  "Logistics, Shipping & Ports",
  "Aviation & Aerospace",
  "Manufacturing & Industrial",
  "Media, Entertainment & Gaming",
  "Education & Training",
  "Professional Services",
  "Government, Public Sector & Non-Profit",
  "Conglomerates / Family Groups / Holdings",
] as const;

export type Sector = (typeof SECTORS)[number];

// Used at query time to expand a mandate's target sectors into adjacent talent
// pools (the "AI suggests adjacent sectors" banner). Not used during enrichment.
export const ADJACENCY: Record<string, string[]> = {
  "Banking & Financial Services": [
    "Capital Markets & Asset Management",
    "Insurance",
    "Technology & Software",
  ],
  "Insurance": [
    "Banking & Financial Services",
    "Healthcare & Pharmaceuticals",
    "Capital Markets & Asset Management",
  ],
  "Capital Markets & Asset Management": [
    "Banking & Financial Services",
    "Insurance",
    "Professional Services",
  ],
  "Real Estate Development": [
    "Construction & Engineering",
    "Hospitality, Travel & Tourism",
    "Conglomerates / Family Groups / Holdings",
  ],
  "Construction & Engineering": [
    "Real Estate Development",
    "Oil & Gas - Downstream / Petrochemicals",
    "Manufacturing & Industrial",
  ],
  "Oil & Gas - Upstream": [
    "Oil & Gas - Downstream / Petrochemicals",
    "Power & Utilities",
    "Manufacturing & Industrial",
  ],
  "Oil & Gas - Downstream / Petrochemicals": [
    "Oil & Gas - Upstream",
    "Manufacturing & Industrial",
    "Logistics, Shipping & Ports",
  ],
  "Power & Utilities": [
    "Oil & Gas - Upstream",
    "Construction & Engineering",
    "Manufacturing & Industrial",
  ],
  "Telecommunications": [
    "Technology & Software",
    "Media, Entertainment & Gaming",
    "Professional Services",
  ],
  "Technology & Software": [
    "Telecommunications",
    "Banking & Financial Services",
    "Media, Entertainment & Gaming",
  ],
  "Consumer Goods": [
    "Retail & E-Commerce",
    "Manufacturing & Industrial",
    "Logistics, Shipping & Ports",
  ],
  "Retail & E-Commerce": [
    "Consumer Goods",
    "Hospitality, Travel & Tourism",
    "Logistics, Shipping & Ports",
  ],
  "Hospitality, Travel & Tourism": [
    "Aviation & Aerospace",
    "Retail & E-Commerce",
    "Real Estate Development",
  ],
  "Healthcare & Pharmaceuticals": [
    "Insurance",
    "Manufacturing & Industrial",
    "Education & Training",
  ],
  "Logistics, Shipping & Ports": [
    "Retail & E-Commerce",
    "Aviation & Aerospace",
    "Manufacturing & Industrial",
  ],
  "Aviation & Aerospace": [
    "Logistics, Shipping & Ports",
    "Hospitality, Travel & Tourism",
    "Manufacturing & Industrial",
  ],
  "Manufacturing & Industrial": [
    "Construction & Engineering",
    "Logistics, Shipping & Ports",
    "Consumer Goods",
  ],
  "Media, Entertainment & Gaming": [
    "Technology & Software",
    "Telecommunications",
    "Professional Services",
  ],
  "Education & Training": [
    "Professional Services",
    "Healthcare & Pharmaceuticals",
    "Technology & Software",
  ],
  "Professional Services": [
    "Banking & Financial Services",
    "Capital Markets & Asset Management",
    "Conglomerates / Family Groups / Holdings",
  ],
  "Government, Public Sector & Non-Profit": [
    "Professional Services",
    "Construction & Engineering",
    "Healthcare & Pharmaceuticals",
  ],
  "Conglomerates / Family Groups / Holdings": [
    "Real Estate Development",
    "Retail & E-Commerce",
    "Hospitality, Travel & Tourism",
  ],
};

export const EMPLOYEE_BANDS = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1k",
  "1k-5k",
  "5k-10k",
  "10k+",
] as const;

export const REVENUE_BANDS = [
  "<$10M",
  "$10-50M",
  "$50-250M",
  "$250M-1B",
  "$1-10B",
  ">$10B",
] as const;

// Controlled sub-tag vocabulary (kebab-case). company_enrichment.sub_tags[] is
// drawn from this closed list so the universe builder matches via array overlap
// without vocabulary drift.
export const SUB_TAGS_BY_SECTOR: Record<string, string[]> = {
  "Banking & Financial Services": [
    "retail-banking",
    "corporate-banking",
    "investment-banking",
    "private-banking",
    "islamic-banking",
    "sme-lending",
    "consumer-credit",
    "mortgage-financing",
    "buy-now-pay-later",
    "fintech-lending",
    "fintech-payments",
    "fintech-neobank",
    "trade-finance",
    "microfinance",
    "credit-cards",
  ],
  "Insurance": [
    "life-insurance",
    "health-insurance",
    "general-insurance",
    "reinsurance",
    "takaful",
    "insurance-brokerage",
    "marine-insurance",
    "motor-insurance",
    "property-casualty-insurance",
    "insurtech",
    "employee-benefits",
    "claims-management",
  ],
  "Capital Markets & Asset Management": [
    "asset-management",
    "wealth-management",
    "private-equity",
    "venture-capital",
    "hedge-fund",
    "sovereign-wealth-fund",
    "family-office",
    "real-estate-fund",
    "sukuk-issuance",
    "investment-advisory",
    "brokerage-equities",
    "brokerage-fx",
    "custody-services",
    "fund-administration",
  ],
  "Real Estate Development": [
    "residential-development",
    "luxury-residential",
    "commercial-real-estate",
    "mixed-use-development",
    "master-planned-communities",
    "retail-mall-development",
    "hospitality-real-estate",
    "industrial-real-estate",
    "real-estate-brokerage",
    "facilities-management",
    "property-management",
    "real-estate-investment",
    "reits",
    "proptech",
  ],
  "Construction & Engineering": [
    "general-contracting",
    "epc-contractor",
    "mep-contracting",
    "civil-infrastructure",
    "infrastructure-development",
    "roads-bridges",
    "marine-construction",
    "interior-fitout",
    "structural-engineering",
    "architecture-design",
    "project-management-construction",
    "facade-engineering",
    "modular-construction",
    "building-materials-construction",
  ],
  "Oil & Gas - Upstream": [
    "exploration-production",
    "offshore-drilling",
    "onshore-drilling",
    "reservoir-engineering",
    "seismic-services",
    "well-services",
    "oilfield-services",
    "subsea-engineering",
    "lng-upstream",
    "shale-tight-oil",
    "production-optimization",
    "decommissioning-upstream",
  ],
  "Oil & Gas - Downstream / Petrochemicals": [
    "refining",
    "petrochemicals",
    "polymers-plastics",
    "fertilizers",
    "lng-downstream",
    "fuel-retail",
    "lubricants-blending",
    "gas-distribution",
    "industrial-gases",
    "downstream-trading",
    "specialty-chemicals",
    "pipeline-operations",
  ],
  "Power & Utilities": [
    "power-generation-thermal",
    "renewable-solar",
    "renewable-wind",
    "renewable-hydro",
    "nuclear-power",
    "power-transmission",
    "power-distribution",
    "water-desalination",
    "water-treatment",
    "waste-management",
    "district-cooling",
    "energy-trading",
    "grid-tech",
  ],
  "Telecommunications": [
    "mobile-network-operator",
    "fixed-line-broadband",
    "fiber-rollout",
    "5g-infrastructure",
    "tower-infrastructure",
    "data-centers",
    "submarine-cable",
    "mvno",
    "satellite-comms",
    "iot-connectivity",
    "telecom-managed-services",
    "telecom-distribution",
  ],
  "Technology & Software": [
    "enterprise-saas",
    "cloud-infrastructure",
    "cybersecurity",
    "data-analytics",
    "ai-ml-platform",
    "ecommerce-platform",
    "fintech-software",
    "healthtech-software",
    "edtech-software",
    "devtools",
    "it-services",
    "it-services-systems-integration",
    "hardware-iot",
    "ar-vr",
    "blockchain-crypto",
    "digital-platforms",
  ],
  "Consumer Goods": [
    "fmcg-manufacturing",
    "food-beverage-brand",
    "beauty-cosmetics",
    "personal-care",
    "household-products",
    "consumer-products",
    "home-furnishings",
    "jewelry-watches",
  ],
  "Retail & E-Commerce": [
    "fashion-apparel",
    "luxury-retail",
    "grocery-supermarket",
    "consumer-electronics",
    "electronics-retail",
    "automotive-retail",
    "ecommerce-retailer",
    "department-store",
    "specialty-retail",
    "mobile-devices",
    "omnichannel-retail",
  ],
  "Hospitality, Travel & Tourism": [
    "hotels-luxury",
    "hotels-midscale",
    "resorts",
    "serviced-apartments",
    "restaurants-fb",
    "qsr-fast-casual",
    "cafes-coffee",
    "food-service",
    "destination-management",
    "tour-operator",
    "travel-agency-otas",
    "cruise-yachting",
    "events-conferences",
    "theme-parks-attractions",
  ],
  "Healthcare & Pharmaceuticals": [
    "hospitals-multispecialty",
    "specialty-clinics",
    "primary-care",
    "diagnostic-imaging",
    "laboratory-services",
    "pharmaceutical-manufacturing",
    "pharma-distribution",
    "medical-devices",
    "biotech-research",
    "telehealth",
    "digital-health",
    "pharmacy-retail",
    "home-healthcare",
  ],
  "Logistics, Shipping & Ports": [
    "freight-forwarding",
    "3pl-warehousing",
    "last-mile-delivery",
    "shipping-lines",
    "port-operations",
    "cold-chain-logistics",
    "express-courier",
    "supply-chain-management",
    "customs-brokerage",
    "intermodal-rail",
    "trucking-road-freight",
    "logistics-distribution",
    "logistics-tech",
  ],
  "Aviation & Aerospace": [
    "passenger-airline",
    "cargo-airline",
    "low-cost-carrier",
    "airport-operations",
    "ground-handling",
    "aviation-services",
    "mro-aircraft-maintenance",
    "aircraft-leasing",
    "aerospace-manufacturing",
    "defense-aviation",
    "satellite-services",
    "drone-uav",
    "business-aviation",
  ],
  "Manufacturing & Industrial": [
    "steel-metals",
    "aluminum-smelting",
    "cement-building-materials",
    "glass-ceramics",
    "industrial-equipment",
    "automotive-components",
    "food-processing",
    "textiles-apparel-manufacturing",
    "packaging",
    "heavy-machinery",
    "electrical-equipment",
    "industrial-automation",
    "contract-manufacturing",
  ],
  "Media, Entertainment & Gaming": [
    "broadcasting-tv",
    "radio",
    "print-publishing",
    "digital-publishing",
    "advertising-agency",
    "media-buying",
    "pr-communications",
    "film-production",
    "music-recording",
    "gaming-esports",
    "streaming-platforms",
    "influencer-creator-economy",
  ],
  "Education & Training": [
    "k12-schools",
    "higher-education-university",
    "vocational-training",
    "edtech-platforms",
    "corporate-training",
    "language-training",
    "professional-certifications",
    "test-prep",
    "tutoring-services",
    "early-childhood-education",
    "online-courses-mooc",
    "executive-education",
  ],
  "Professional Services": [
    "management-consulting",
    "strategy-consulting",
    "audit-assurance",
    "tax-advisory",
    "legal-services",
    "executive-search",
    "staffing-recruitment",
    "real-estate-advisory",
    "marketing-research",
    "engineering-consulting",
    "actuarial-services",
    "outsourcing-bpo",
    "facilities-management-services",
  ],
  "Government, Public Sector & Non-Profit": [
    "government-entity",
    "regulatory-body",
    "ngo",
    "international-organisation",
    "public-sector-agency",
    "defense-public",
  ],
  "Conglomerates / Family Groups / Holdings": [
    "family-business-group",
    "family-office-operating",
    "diversified-holding",
    "investment-holding",
    "trading-group",
    "industrial-conglomerate",
    "ruling-family-holding",
    "sovereign-holding",
    "regional-distributor-group",
    "multi-sector-investment-group",
  ],
};

// Flat canonical set for O(1) membership validation.
export const SUB_TAGS: Set<string> = new Set(
  Object.values(SUB_TAGS_BY_SECTOR).flat(),
);

export const SECTOR_SET: Set<string> = new Set(SECTORS);
export const EMPLOYEE_BAND_SET: Set<string> = new Set(EMPLOYEE_BANDS);
export const REVENUE_BAND_SET: Set<string> = new Set(REVENUE_BANDS);

// Adjacent sectors for a set of primary sectors, deduped and excluding the
// primaries themselves.
export function adjacentSectorsFor(primarySectors: string[]): string[] {
  const primarySet = new Set(primarySectors);
  const out = new Set<string>();
  for (const sector of primarySectors) {
    for (const adj of ADJACENCY[sector] ?? []) {
      if (!primarySet.has(adj)) out.add(adj);
    }
  }
  return [...out];
}
